name: banco-extension-template
authors:
  - myth-MC
  - U8092
version: 1.0.0
api-version: '1.20'

main: ovh.mythmc.bancoextensiontemplate.BancoExtensionTemplate

dependencies:
  server:
    banco:
      load: BEFORE
      required: true